sonar.projectKey=dongoctho_webthuongmaidientubandogiadung
sonar.organization=b23ec527501533c764d4d1676526be47e92eea35

sonar.sources=.

sonar.exclusions=\
vendor/**,\
node_modules/**,\
storage/**,\
bootstrap/cache/**,\
public/**

sonar.sourceEncoding=UTF-8
